//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enVisioner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("enVisioner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Level.
        /// </summary>
        internal static string EN_Hint_NewFile {
            get {
                return ResourceManager.GetString("EN_Hint_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string EN_Hint_Title {
            get {
                return ResourceManager.GetString("EN_Hint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string EN_Root_Loading_Ready {
            get {
                return ResourceManager.GetString("EN_Root_Loading_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EN_Root_Menu_Edit {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string EN_Root_Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string EN_Root_Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string EN_Root_Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string EN_Root_Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string EN_Root_Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string EN_Root_Menu_File {
            get {
                return ResourceManager.GetString("EN_Root_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EN_Root_Menu_File_Exit {
            get {
                return ResourceManager.GetString("EN_Root_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string EN_Root_Menu_File_New {
            get {
                return ResourceManager.GetString("EN_Root_Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string EN_Root_Menu_File_Open {
            get {
                return ResourceManager.GetString("EN_Root_Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files....
        /// </summary>
        internal static string EN_Root_Menu_File_RF {
            get {
                return ResourceManager.GetString("EN_Root_Menu_File_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EN_Root_Menu_File_Save {
            get {
                return ResourceManager.GetString("EN_Root_Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string EN_Root_Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("EN_Root_Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string EN_Root_Menu_Help {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string EN_Root_Menu_Level {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Tool.
        /// </summary>
        internal static string EN_Root_Menu_Level_Link {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Level_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string EN_Root_Menu_Level_Obj {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Level_Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string EN_Root_Menu_Windows {
            get {
                return ResourceManager.GetString("EN_Root_Menu_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enViSiONer_v0.04.
        /// </summary>
        internal static string EN_Root_Title {
            get {
                return ResourceManager.GetString("EN_Root_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新レベル.
        /// </summary>
        internal static string JP_Hint_NewFile {
            get {
                return ResourceManager.GetString("JP_Hint_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string JP_Hint_Title {
            get {
                return ResourceManager.GetString("JP_Hint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 準備完了.
        /// </summary>
        internal static string JP_Root_Loading_Ready {
            get {
                return ResourceManager.GetString("JP_Root_Loading_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string JP_Root_Menu_Edit {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コピー.
        /// </summary>
        internal static string JP_Root_Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切る.
        /// </summary>
        internal static string JP_Root_Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペースト.
        /// </summary>
        internal static string JP_Root_Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やり直し.
        /// </summary>
        internal static string JP_Root_Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元に戻す.
        /// </summary>
        internal static string JP_Root_Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル.
        /// </summary>
        internal static string JP_Root_Menu_File {
            get {
                return ResourceManager.GetString("JP_Root_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出口.
        /// </summary>
        internal static string JP_Root_Menu_File_Exit {
            get {
                return ResourceManager.GetString("JP_Root_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新着.
        /// </summary>
        internal static string JP_Root_Menu_File_New {
            get {
                return ResourceManager.GetString("JP_Root_Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開いた.
        /// </summary>
        internal static string JP_Root_Menu_File_Open {
            get {
                return ResourceManager.GetString("JP_Root_Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近使用したファイル．．．.
        /// </summary>
        internal static string JP_Root_Menu_File_RF {
            get {
                return ResourceManager.GetString("JP_Root_Menu_File_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブ.
        /// </summary>
        internal static string JP_Root_Menu_File_Save {
            get {
                return ResourceManager.GetString("JP_Root_Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前を付けて保存．．．.
        /// </summary>
        internal static string JP_Root_Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("JP_Root_Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 助けて.
        /// </summary>
        internal static string JP_Root_Menu_Help {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        internal static string JP_Root_Menu_Level {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リンクツール.
        /// </summary>
        internal static string JP_Root_Menu_Level_Link {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Level_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オブジェクト.
        /// </summary>
        internal static string JP_Root_Menu_Level_Obj {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Level_Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウズ.
        /// </summary>
        internal static string JP_Root_Menu_Windows {
            get {
                return ResourceManager.GetString("JP_Root_Menu_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クロノアレベルエディタ＿ｖ０．０４.
        /// </summary>
        internal static string JP_Root_Title {
            get {
                return ResourceManager.GetString("JP_Root_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_ARC {
            get {
                object obj = ResourceManager.GetObject("MDI_ARC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_BACK {
            get {
                object obj = ResourceManager.GetObject("MDI_BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_BLD {
            get {
                object obj = ResourceManager.GetObject("MDI_BLD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_BOOK {
            get {
                object obj = ResourceManager.GetObject("MDI_BOOK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_BUTTON {
            get {
                object obj = ResourceManager.GetObject("MDI_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_CAMERA {
            get {
                object obj = ResourceManager.GetObject("MDI_CAMERA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_CNT {
            get {
                object obj = ResourceManager.GetObject("MDI_CNT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_COPY {
            get {
                object obj = ResourceManager.GetObject("MDI_COPY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_CTR {
            get {
                object obj = ResourceManager.GetObject("MDI_CTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_CUT {
            get {
                object obj = ResourceManager.GetObject("MDI_CUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_DBLUNDR {
            get {
                object obj = ResourceManager.GetObject("MDI_DBLUNDR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_DELETE {
            get {
                object obj = ResourceManager.GetObject("MDI_DELETE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_DISCNET {
            get {
                object obj = ResourceManager.GetObject("MDI_DISCNET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_DRAWING {
            get {
                object obj = ResourceManager.GetObject("MDI_DRAWING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_ELLIPSE {
            get {
                object obj = ResourceManager.GetObject("MDI_ELLIPSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_FIND {
            get {
                object obj = ResourceManager.GetObject("MDI_FIND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_FLAGJP {
            get {
                object obj = ResourceManager.GetObject("MDI_FLAGJP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_FLAGUS {
            get {
                object obj = ResourceManager.GetObject("MDI_FLAGUS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_FREEFORM {
            get {
                object obj = ResourceManager.GetObject("MDI_FREEFORM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_FRONT {
            get {
                object obj = ResourceManager.GetObject("MDI_FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_GROUP {
            get {
                object obj = ResourceManager.GetObject("MDI_GROUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_HELP {
            get {
                object obj = ResourceManager.GetObject("MDI_HELP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_HELP2 {
            get {
                object obj = ResourceManager.GetObject("MDI_HELP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_INFOPAGE {
            get {
                object obj = ResourceManager.GetObject("MDI_INFOPAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_ITL {
            get {
                object obj = ResourceManager.GetObject("MDI_ITL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_JST {
            get {
                object obj = ResourceManager.GetObject("MDI_JST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_LFT {
            get {
                object obj = ResourceManager.GetObject("MDI_LFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_LINE {
            get {
                object obj = ResourceManager.GetObject("MDI_LINE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_LINESTYL {
            get {
                object obj = ResourceManager.GetObject("MDI_LINESTYL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_LINK {
            get {
                object obj = ResourceManager.GetObject("MDI_LINK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_MAPNET {
            get {
                object obj = ResourceManager.GetObject("MDI_MAPNET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_MCR {
            get {
                object obj = ResourceManager.GetObject("MDI_MCR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_NEW {
            get {
                object obj = ResourceManager.GetObject("MDI_NEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_newobj {
            get {
                object obj = ResourceManager.GetObject("MDI_newobj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_OPEN {
            get {
                object obj = ResourceManager.GetObject("MDI_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_PASTE {
            get {
                object obj = ResourceManager.GetObject("MDI_PASTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_PRINT {
            get {
                object obj = ResourceManager.GetObject("MDI_PRINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_PROP {
            get {
                object obj = ResourceManager.GetObject("MDI_PROP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_RECTANGL {
            get {
                object obj = ResourceManager.GetObject("MDI_RECTANGL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_REDO {
            get {
                object obj = ResourceManager.GetObject("MDI_REDO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_RT {
            get {
                object obj = ResourceManager.GetObject("MDI_RT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_SAVE {
            get {
                object obj = ResourceManager.GetObject("MDI_SAVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_SMALLCAP {
            get {
                object obj = ResourceManager.GetObject("MDI_SMALLCAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_SORTASC {
            get {
                object obj = ResourceManager.GetObject("MDI_SORTASC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_SORTDES {
            get {
                object obj = ResourceManager.GetObject("MDI_SORTDES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_SPELLING {
            get {
                object obj = ResourceManager.GetObject("MDI_SPELLING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_STRIKTHR {
            get {
                object obj = ResourceManager.GetObject("MDI_STRIKTHR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_SUM {
            get {
                object obj = ResourceManager.GetObject("MDI_SUM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_TABCNTR {
            get {
                object obj = ResourceManager.GetObject("MDI_TABCNTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_TABDEC {
            get {
                object obj = ResourceManager.GetObject("MDI_TABDEC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_TABLEFT {
            get {
                object obj = ResourceManager.GetObject("MDI_TABLEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_TABRHT {
            get {
                object obj = ResourceManager.GetObject("MDI_TABRHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_UNDO {
            get {
                object obj = ResourceManager.GetObject("MDI_UNDO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_UNDRLN {
            get {
                object obj = ResourceManager.GetObject("MDI_UNDRLN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_UNGROUP {
            get {
                object obj = ResourceManager.GetObject("MDI_UNGROUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_UP1LVL {
            get {
                object obj = ResourceManager.GetObject("MDI_UP1LVL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_VWDTLS {
            get {
                object obj = ResourceManager.GetObject("MDI_VWDTLS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_VWLIST {
            get {
                object obj = ResourceManager.GetObject("MDI_VWLIST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_VWLRGIC {
            get {
                object obj = ResourceManager.GetObject("MDI_VWLRGIC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_VWSMLIC {
            get {
                object obj = ResourceManager.GetObject("MDI_VWSMLIC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDI_WORDUNDR {
            get {
                object obj = ResourceManager.GetObject("MDI_WORDUNDR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_5g {
            get {
                object obj = ResourceManager.GetObject("spr_5g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy {
            get {
                object obj = ResourceManager.GetObject("spr_enemy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy2 {
            get {
                object obj = ResourceManager.GetObject("spr_enemy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy3 {
            get {
                object obj = ResourceManager.GetObject("spr_enemy3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy4 {
            get {
                object obj = ResourceManager.GetObject("spr_enemy4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy5 {
            get {
                object obj = ResourceManager.GetObject("spr_enemy5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy6 {
            get {
                object obj = ResourceManager.GetObject("spr_enemy6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy7 {
            get {
                object obj = ResourceManager.GetObject("spr_enemy7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_enemy8 {
            get {
                object obj = ResourceManager.GetObject("spr_enemy8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_gem {
            get {
                object obj = ResourceManager.GetObject("spr_gem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_heal {
            get {
                object obj = ResourceManager.GetObject("spr_heal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_key {
            get {
                object obj = ResourceManager.GetObject("spr_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_life {
            get {
                object obj = ResourceManager.GetObject("spr_life", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_ply {
            get {
                object obj = ResourceManager.GetObject("spr_ply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spr_star {
            get {
                object obj = ResourceManager.GetObject("spr_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
